name: Build & Deploy to GH Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'    # jede Stunde

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 1) Build & run fetcher (Server-only)
      - name: Install Server Dependencies
        run: |
          cd server
          npm install

      - name: Build Server
        run: |
          cd server
          npm run build

      - name: Run Fetcher to populate data/
        # Wir führen nur das UpdateAll-Skript aus, nicht den Webserver dauerhaft
        run: |
          node server/dist/server/index.js --only-fetch
        # Passe deine index.ts so an, dass bei --only-fetch nur fetchAll läuft und dann exit

      # 2) Build Frontend into docs/
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build --outDir ../docs

      # 3) Copy the freshly populated data folder
      - name: Copy data into docs
        run: |
          mkdir -p docs/data
          cp -r data/* docs/data/

      # 4) Deploy to GH Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: docs
